apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: service1
      service.name: service1-service
  replicas: 1
  template:
    metadata:
      labels:
        app: service1
        service.name: service1-service
    spec:
      containers:
      - name: service1
        image: stacksimplify/kube-nginxapp1:1.0.0
        ports:
            - containerPort: 80
