apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
spec:
  selector:
    matchLabels:
      app: service1
      service.name: service1-service
  replicas: 1
  template:
    metadata:
      labels:
        app: service1
        service.name: service1-service
    spec:
      containers:
      - name: service1
        image: asia-south1-docker.pkg.dev/cision-ness/ness-docker-repo/service1:v200
