apiVersion: v1
kind: Service
metadata:
  name: service1-service
  namespace: argocd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
  labels:
    app: service1
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
