apiVersion: v1
kind: Service
metadata:
  name: service1-service
  namespace: argocd
  annotations:
    service.beta.kubernetes.io/gcp-load-balancer-internal: 'true'
spec:
  ports:
  - name: "docker-port"
    port: 8080
    targetPort: 8080
  - name: "http-port"
    port: 80
    targetPort: 8080
  type: NodePort	  
