apiVersion: v1
kind: Service
metadata:
  namespace: yogi
  name: service1-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: service1
    service.name: service1-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
