apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  type: ClusterIP
  selector:
    app: service1
    service.name: service1-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
