apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cpr
  annotations:
    # External Load Balancer  
    kubernetes.io/ingress.class: "gce"  
spec: 
  defaultBackend:
    service:
      name: service1-service
      port:
        number: 8080
  rules:
    - http:
        paths:           
          - path: /getData1
            pathType: Prefix
            backend:
              service:
                name: service1-service
                port: 
                  number: 8080
          - path: /swagger-ui/index.html
            pathType: Prefix
            backend:
              service:
                name: service1-service
                port: 
                  number: 8080
